use finalproject;

INSERT INTO users (username, email, password) VALUES
("Person_1", "person1@finalproject.com", "asdf1234"),
("Person_2", "person2@finalproject.com", "asdf1234"),
("Person_3", "person3@finalproject.com", "asdf1234"),
("Person_4", "person4@finalproject.com", "asdf1234"),
("Person_5", "person5@finalproject.com", "asdf1234"),
("Person_6", "person6@finalproject.com", "asdf1234"),
("Person_7", "person7@finalproject.com", "asdf1234"),
("Person_8", "person8@finalproject.com", "asdf1234"),
("Person_9", "person9@finalproject.com", "asdf1234"),
("Person_10", "person10@finalproject.com", "asdf1234"),
("Person_11", "person11@finalproject.com", "asdf1234"),
("Person_12", "person12@finalproject.com", "asdf1234"),
("Person_13", "person13@finalproject.com", "asdf1234"),
("Person_14", "person14@finalproject.com", "asdf1234"),
("Person_15", "person15@finalproject.com", "asdf1234"),
("Person_16", "person16@finalproject.com", "asdf1234");

INSERT INTO descriptions (age, gender, orientation, ethnicity, height) VALUES
(21, "Male", "Straight", "White", "5'10"),
(18, "Female", "Lesbian", "White", "5'6"),
(23, "Male", "Gay", "Latino", "6'1"),
(25, "Female", "Straight", "Black", "5'8"),
(26, "Male", "Straight", "Asian", "5'7"),
(24, "Female", "Straight", "Middle Eastern", "5'3"),
(28, "Trans Man", "Bisexual", "Latino", "5'5"),
(27, "Female", "Bisexual", "Native American", "5'2"),
(20, "Male", "Gay", "Pacific Islander", "5'10"),
(20, "Trans Woman", "Pansexual", "Asian", "5'9"),
(21, "Non-Binary", "Pansexual", "White", "6'0"),
(24, "Trans Man", "Straight", "Black", "5'7"),
(26, "Non-Binary", "Queer", "White", "5'5"),
(30, "Questioning", "Questioning", "White", "5'10"),
(29, "Intersex", "Asexual", "White", "5'7"),
(21, "Prefer Not to Say", "Prefer Not to Say", "White", "5'5");

INSERT INTO locations (city, state) VALUES
("Birmingham","Alabama"),
("Hoover","Alabama"),
("Trussville","Alabama"),
("Bessemer","Alabama"),
("Pelham","Alabama"),
("Alabaster","Alabama"),
("Vestavia Hills","Alabama"),
("Hoover","Alabama"),
("Birmingham","Alabama"),
("Hoover","Alabama"),
("Trussville","Alabama"),
("Bessemer","Alabama"),
("Pelham","Alabama"),
("Alabaster","Alabama"),
("Vestavia Hills","Alabama"),
("Hoover","Alabama");

INSERT INTO hobbies (sports, foodie, running, travel, movies, reading, 
fashion, videogames, dancing, cycling, music, swimming, hiking, excercising,
concerts, art, cooking, singing, baking, animals, camping, boardgames, crafts) VALUES
(true, false, true, false, true, false, false, true, false, false, true, false, false, true, true, false, false, false, false, true, true, false, false),
(false, true, false, true, true, true, true, false, false, false, true, false, false, false, false, true, true, false, true, true, false, false, true),
(false, false, false, true, true, false, true, true, true, false, true, false, false, true, true, true, false, false, false, false, false, false, true),
(true, false, true, false, false, false, false, false, true, true, false, false, false, true, false, true, true, true, false, true, false, true, false),
(false, true, false, true, true, true, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false),
(true, true, false, false, false, true, false, false, false, false, false, false, true, true, true, false, true, false, false, false, false, true, false),
(true, false, true, false, true, false, true, false, true, false, true, false, false, true, false, false, false, false, true, false, true, true, false),
(false, true, true, false, false, true, false, false, true, true, true, false, true, true, false, false, false, true, true, true, false, false, false),
(false, false, false, true, true, true, false, true, false, false, true, true, false, false, true, true, true, true, false, false, false, false, true),
(false, false, false, true, false, true, true, true, true, false, true, false, false, false, true, false, true, false, true, true, false, false, true),
(false, false, true, true, true, true, false, false, true, false, true, true, true, true, false, true, false, false, false, true, true, false, false),
(true, true, true, false, true, false, false, true, false, false, true, false, false, true, false, false, false, true, false, false, false, false, true),
(false, true, false, true, true, true, true, false, false, false, true, false, false, true, true, true, false, false, true, false, true, true, false),
(false, true, false, true, true, true, false, false, false, false, true, true, false, true, true, false, true, false, false, false, false, true, false),
(false, true, false, true, true, true, true, false, true, false, true, false, false, false, true, true, false, true, false, true, false, true, false),
(false, false, false, false, true, true, false, true, false, false, true, false, false, false, false, false, true, true, false, true, false, false, true);

INSERT INTO sensorytags (hypersight, hypersound, hypersmell, hypertaste, hypertouch, hyposight, hyposound,
hyposmell, hypotaste, hypotouch, balance, bodyawareness) VALUES
(false, false, false, false, false, false, true, false, false, false, false, true),
(false, true, false, false, false, false, false, false, false, true, false, false),
(false, false, true, false, false, false, true, false, false, false, false, false),
(false, false, false, true, false, false, true, false, false, false, false, false),
(false, false, false, false, true, false, true, false, false, false, false, false),
(false, false, false, true, false, false, false, true, false, false, false, false),
(false, false, true, false, false, false, false, true, true, false, false, false),
(false, true, false, false, false, false, false, true, true, false, false, false),
(true, false, false, false, false, false, false, false, true, false, false, false),
(false, true, false, true, false, false, false, false, false, false, true, false),
(true, false, true, false, false, false, false, false, false, false, false, false),
(true, true, false, false, false, false, false, false, false, false, false, true),
(false, true, false, false, true, false, false, false, false, false, false, true),
(true, false, false, false, false, false, false, false, false, false, false, true),
(false, false, true, true, false, false, false, false, false, false, true, false),
(false, false, false, false, true, false, false, true, false, false, false, true);

INSERT INTO profileinfo (userid, firstname, image, bio, spectrum, relationship, descriptionid, locationid, hobbiesid, sensoryid) VALUES
(1, "Joe", "https://media.istockphoto.com/photos/happy-smiling-man-looking-away-picture-id1158245623?k=6&m=1158245623&s=612x612&w=0&h=y0LbpRFMHMj_9YC_kpKvLYcijEunxP27KyjXBrDHcFg=", "Hi! I'm Joe.  I like football.", "Autistic", "Friendship", 1, 1, 1, 1),
(2, "Jane", "https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/386-mj-1671-ae.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=8ce11305f86caccab7046fa4b00c4cde", "Hi! I'm Jane.  Let's hangout.", "Person with Autism", "Relationship", 2, 2, 2, 2),
(3, "Tanner", "https://image.shutterstock.com/mosaic_250/2936380/640011838/stock-photo-handsome-unshaven-young-dark-skinned-male-laughing-out-loud-at-funny-meme-he-found-on-internet-640011838.jpg", "No Pic, No Chat", "On the Spectrum", "Relationship", 3, 3, 3, 3),
(4, "Katie", "https://images.newrepublic.com/9351cbab311e60a47aae74635034b466c5acba5a.jpeg?auto=compress&w=1400&ar=3%3A2&fit=crop&crop=faces&q=65&fm=jpg&ixlib=react-9.0.2", "I'm bad at making profiles.  Just message me.", "Autistic", "Relationship", 4, 4, 4, 4),
(5, "Brian", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA-Vy1U2EycMeV75CnbgGTI45yGT2yKJ0p3g&usqp=CAU", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Autistic", "Other", 5, 5, 5, 5),
(6, "Hannah", "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8d2hpdGUlMjBwZXJzb258ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Person with Autism", "Relationship", 6, 6, 6, 6),
(7, "Clark", "https://media.istockphoto.com/photos/portrait-of-men-looking-at-camera-picture-id1181083533?k=6&m=1181083533&s=612x612&w=0&h=1l45cytyMWyEwWMtZf0vKPyV5cwy5hIDvoA_Zysi6g8=", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Autistic", "Friendship", 7, 7, 7, 7),
(8, "Emily", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP_yKvluISKD8MQuZgwZu5HokLVzbcF3SAnA&usqp=CAU", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Autistic Person", "Relationship", 8, 8, 8, 8),
(9, "Sean", "https://media.istockphoto.com/photos/photo-hui-business-group-shoot-picture-id895886272?k=6&m=895886272&s=612x612&w=0&h=DK1cnmgdnSvhZJP8Nu6PCYzhIBVNuIy40k8j3qv5LWE=", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Autistic", "Friendship", 9, 9, 9, 9),
(10, "Lizzie", "https://dynaimage.cdn.cnn.com/cnn/q_auto,w_380,c_fit/http%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F210317104652-07-asian-americans-beauty-industry-restricted.jpg", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "On the Spectrum", "Relationship", 10, 10, 10, 10),
(11, "Sky", "https://images.unsplash.com/photo-1506863530036-1efeddceb993?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmxhY2slMjBhbmQlMjB3aGl0ZSUyMHBlb3BsZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&w=1000&q=80", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "ASD", "Other", 11, 11, 11, 11),
(12, "Kylar", "https://image1.masterfile.com/getImage/NjkzLTA2MDE2Mzk1ZW4uMDAwMDAwMDA=AMAF3A/693-06016395en_Masterfile.jpg", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Asperger's", "Relationship", 12, 12, 12, 12),
(13, "Flo", "https://www.ctvnews.ca/polopoly_fs/1.107622.1337370684!/httpImage/image._gen/derivatives/landscape_620/image.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Austistic", "Relationship", 13, 13, 13, 13),
(14, "Taylor", "https://images.unsplash.com/photo-1568990545613-aa37e9353eb6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8d2hpdGUlMjBtYW58ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Asperger's", "Other", 14, 14, 14, 14),
(15, "West", "https://image.shutterstock.com/image-photo/latin-hipster-guy-wearing-glasses-260nw-333000893.jpg", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Person with Autism", "Relationship", 15, 15, 15, 15),
(16, "Sam", "https://www.8asians.com/wp-content/uploads/2011/11/thanksgiving-stock-photo.jpg", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit amet.", "Autistic", "Friendship", 16, 16, 16, 16);

INSERT INTO activities (name, about, address, link, picture, hours, cost) VALUES
("Birmingham Zoo","A wildlife zoo containing lions, zebras, rhinos, giraffes, and many more animals", "2630 Cahaba Road, Birmingham, AL 35223", "https://www.birminghamzoo.com", "https://www.birminghamzoo.com/wp-content/themes/birminghamzoo.com/style/images/logo.svg", "Wednesday - Sunday: 9:00AM - 5:00PM", 2),
("Vulcan Park and Museum","A beautiful park complete with the largest cast-iron statue in the world and an interactive musuem","1701 Valley View Drive, Birmingham, AL 35209","https://visitvulcan.com","https://visitvulcan.com/wp-content/themes/visit-vulcan/images/vulcan-fill-logo.svg", "Park Grounds: Everyday 10:00AM - 10:00PM, Vulcan Center: Weekends 10:00AM - 6:00 PM", 1),
("Oak Mountain State Park","Beautiful State Park full of hiking trails and other outdoor activities, including camping.","200 Terrace Drive, Pelham, AL 35124","https://www.alapark.com/parks/oak-mountain-state-park","https://www.alapark.com/themes/custom/alapark/logo.svg", "7:00AM - 7:00PM", 1),
("Sloss Furnaces","Once the largest manufacturer of pig iron in the world, now a national historic landmark.","20 32nd Street North, Birmingham, AL 35222","https://www.slossfurnaces.com","https://www.slossfurnaces.com/wp-content/uploads/2015/06/rotator-04.jpg", "Tuesday - Saturday: 10:00AM - 4:00PM, Sunday: 12:00PM - 4:00PM", 0),
("SAW's Soul Kitchen","Classic American BBQ and Soul Food Restaurant", "215 41st St S, Birmingham, AL 35222","http://www.sawsbbq.com/","https://www.sawsbbq.com/core/uploads/2019/08/SAWS-Logo.svg","11:00AM - 8:00PM", 1),
("Yo' Mama's","Classic American Style Food","2328 2nd Ave N, Birmingham, AL 35203", "https://www.yomamasrestaurant.com", "https://www.yomamasrestaurant.com/wp-content/themes/espresso/images/logo@2x.png","Mon  Fri 10:30AM - 2:30PM", 1),
("El Barrio","Mexican/Southwestern Restaurant","2211 2nd Ave N, Birmingham, AL 35203","http://elbarriobirmingham.com/","https://images.squarespace-cdn.com/content/v1/601759992e514a5b86ee0180/1624502569493-JNU3ONFVT7IJL4B7RO6O/elbarrio-logo-newAsset+2%402x.png?format=1500w", "Sunday - Monday: Closed, Tuesday - Thursday: 11:30AM - 8:00 PM, Friday - Saturday: 11:30Am - 9:00PM", 2),
("Perry's Steakhouse & Grille","Upscale American Style Steakhouse", "4 Perimeter Park S, Birmingham, AL 35243", "http://www.perryssteakhouse.com/menu-locations/alabama/birmingham/", "https://perryssteakhouse.com/wp-content/themes/perrys-steakhouse/img/Perrys-Steakhouse-Grille-Logo-Col-Opt.svg", "Monday - Thursday: 4PM - 10PM, Friday: 10:30AM - 10:00PM, Saturday: 4:00PM - 10:00PM, Sunday: 4:00PM - 9:00PM", 3);

INSERT INTO questions (sentence) VALUES
("What is your favorite food?"),
("What is your favorite animal?"),
("What is your favorite color?"),
("What is your favorite TV show?"),
("What is your favorite movie?"),
("What do you like to do on the weekends?"),
("If you could travel anywhere in the world, where would you go?"),
("What is your zodiac sign?"),
("What was your favorite school subject?"),
("If you could have a superpower, what would you want?");

INSERT INTO comments (username, commentText) VALUES
("Joe", "I'm so glad to be on iNDie Connect"),
("Jane", "Me too, this website is cool."),
("Tanner", "Glad to meet everyone."),
("Katie", "I'm looking for friends!!!"),
("Brian", "I'll be your friend, Katie!"),
("Joe", "Me too!!!"),
("Jane", "Me three!!!"),
("Tanner", "Who ever made this website must be cool."),
("Katie", "I agree with you Tanner."),
("Tanner", "TY Katie."),
("Brian", "Does anyone want to meet up at the zoo on Friday?"),
("Joe", "Ooo that sounds like tons of fun."),
("Joe", "Count me in."),
("Jane", "I'd love to go to the zoo!");